### ISSUE TITLE
add book club URL query parameter

### ISSUE THREAD

**Issue by tanho63** [r4ds/bookclubber#14]
It would be useful if we could pre-select the book club input via a URL query parameter, e.g.

`https://r4dscommunity.shinyapps.io/bookclubber/?bookclub=RPackages`

**Comment by priyankagagneja** [comment]
Great suggestion Tan, never used this before. I can look into , totally makes sense.

**Comment by priyankagagneja** [comment]
just added this in PR, should hopefully work.
