### ISSUE TITLE
Modal on Save Failure

### ISSUE THREAD

**Issue by jonthegeek** [r4ds/bookclubber#16]
We let them know that their data is submitted (before we save it), but let's add a specific error message if googlesheets4 complains.

**Comment by priyankagagneja** [comment]
I out the modal after sheet_append() dint I inside the observeEvent() ? 
I intended to give the msg after saving it. 

But I agree the failure message makes sense too.

**Comment by jonthegeek** [comment]
I moved it (see changes in a sec) cuz it was still possible to submit multiple times, especially if google was slow.

**Comment by jonthegeek** [comment]
@tanho63 suggested making the modal a "Please wait" (or "Saving data" or whatever), and then either change it to an error (if the save fails) or `shiny::removeModal()` (if the save succeeds). I think. That sounds perfect! See https://rfordatascience.slack.com/archives/C036TFQR210/p1647961900356649 for sample code.
