### ISSUE TITLE
Better Handling of Unavailable Times

### ISSUE THREAD

**Issue by jonthegeek** [r4ds/bookclubber#52]
Right now we hide the unavailable times, but they come back if you tab over them or if you click-and-drag to select a bunch of times and spacebar to toggle them. Is it possible to REALLY get rid of them?

This might require us to use something other than rhandsontable (or otherwise enhance it). I remember I dug through [this site](http://jrowen.github.io/rhandsontable/#Introduction) a lot when I was trying to make things work, but it never QUITE got to perfect. I may have even filed an issue, I need to dig some more.

 That code is really messy and should be cleaned up as part of this ticket, in any case!

**Comment by lucio-cornejo** [comment]
This may be useful: https://jrowen.github.io/rhandsontable/#Read-Only
